# Default values for hello-mr-badger.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

container:
  image: chesnovskii/hello-mr-badger:1.1
  port: 8080

service:
  type: ClusterIP
  port: 8080